baseURL = "https://ipfs-book.decentralized-web.jp"
languageCode = "ja"
title = "IPFS入門"
theme = "hugo-theme-learn"

[params]
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = true
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
  name = "<i class='fa fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/a-mitani/ipfs-primer"
  weight = 10


[[menu.shortcuts]]
  name = "<i class='fa fa-user'></i> Contact"
  url = "https://github.com/a-mitani"
  weight = 30

[[menu.shortcuts]]
  name = "<i class='fa fa-link' aria-hidden='true'></i> Ethereum入門"
  url = "https://book.ethereum-jp.net/"
  weight = 40
